from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
import random

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Example list of values
my_list = [
    "Empower employees to make decisions",
    "Build trust through transparent communication",
    "Hire employees who share your organizational values",
    "Encourage long-term relationships with customers",
    "Focus on creating a positive employee experience to enhance customer service",
    "Adapt services to meet customer needs",
    "Encourage employees to use good judgment in all situations",
    "Personalize the customer experience",
    "Value and act on customer feedback",
    "Make customer relationships a long-term priority over short-term sales",
    "Create a seamless and hassle-free customer experience",
    "Recognize and reward employees for exceptional service",
    "Maintain a consistent brand experience across all touchpoints",
    "Foster a culture of collaboration among employees",
    "Show empathy during customer interactions",
    "Simplify policies to empower employees and satisfy customers",
    "Encourage employees to own the customer experience",
    "Celebrate small wins to reinforce service-oriented behaviour",
    "Innovate based on evolving customer expectations",
    "Empower customers by giving them control",
    "Deliver service as an act of trust and respect",
    "Use storytelling to reinforce company values",
    "Go beyond expectations to create memorable moments",
    "Treat mistakes as learning opportunities",
    "Show customers they are valued through personalization",
    "Always respond to customer complaints",
    "Embrace complaints as opportunities",
    "Personalize your responses",
    "Use complaints to improve your processes",
    "Be quick to acknowledge complaints",
    "Apologize sincerely and take ownership",
    "Respond to positive feedback, too",
    "Use data to prioritize complaints",
    "Resolve issues in one interaction whenever possible",
    "Appreciate even your most difficult customers",
    "Address underlying causes, not just symptoms",
    "Be proactive in seeking customer feedback",
    "Don’t take complaints personally",
    "Avoid overpromising when resolving complaints",
    "Measure success by customer satisfaction, not just resolution speed",
    "Leverage social proof to reinforce resolutions",
    "Respond to criticism even when you can’t resolve the issue",
    "Provide clarity when handling complex issues",
    "Show gratitude for all customer feedback",
    "Avoid automatic or robotic responses",
    "Turn detractors into advocates",
    "Stay calm under pressure",
    "Offer alternate resolutions when necessary",
    "Balance empathy with efficiency",
    "Respond to feedback in the customer’s tone",
    "Focus on Identity-Based Habits",
    "Build Small, Consistent Improvements",
    "Make Actions Attractive",
    "Use the Two-Minute Rule",
    "Focus on Systems, Not Just Goals",
    "Optimize for Convenience",
    "Use Rewards to Reinforce Positive Actions",
    "Create Accountability",
    "Focus on Cues to Trigger Behaviour",
    "Avoid Focusing on Outcomes Alone",
    "Habit Stacking to Build Consistency",
    "Make Habits Satisfying",
    "Break Down Bad Habits",
    "Use Visual Cues",
    "Track Customer Progress",
    "Focus on One Change at a Time",
    "Set Clear Intentions for Every Interaction",
    "Balance Empathy with Efficiency",
    "Celebrate Customer Milestones",
    "Prepare for Difficult Scenarios",
    "Highlight Customer Benefits Clearly",
    "Align Habits With Customer Goals",
    "Use Storytelling to Reinforce Habits",
    "Eliminate Unnecessary Steps",
    "Match Energy Levels to Customer Needs",
    "Reframe Challenges as Opportunities",
    "Cultivate a Growth Mindset",
    "Practice Active Listening",
    "Encourage Collaboration Over Competition",
    "Build Resilience in Adversity",
    "Value Constructive Criticism",
    "Focus on Long-Term Relationships",
    "Embrace Continuous Improvement",
    "Approach Setbacks Strategically",
    "Be Open to Adaptation",
    "Balance Confidence with Humility",
    "Address Customer Concerns Directly",
    "Take Ownership of Mistakes",
    "Encourage Customers to Provide Feedback",
    "Prioritize the Customer’s Experience",
    "Avoid Taking Criticism Personally",
    "Build Trust Through Transparency",
    "Demonstrate Patience",
    "Use Challenges to Showcase Resilience",
    "Turn Criticism into Actionable Steps",
    "Celebrate Small Wins",
    "Avoid Defensive Responses",
    "Encourage Customers to Share Their Stories",
    "Embrace Discomfort as Growth",
    "Focus on Values Over Goals",
    "Take Action Despite Fear",
    "Practice Diffusion from Negative Thoughts",
    "Be Present in the Interaction",
    "Reframe Fear as Motivation",
    "Commit to Small, Consistent Actions",
    "Use Mindfulness to Manage Stress",
    "Build Confidence Through Practice",
    "Step Out of Your Comfort Zone",
    "Create Psychological Flexibility",
    "Learn to Observe, Not React",
    "Address the Problem, Not the Emotion",
    "Use Values to Overcome Challenges",
    "Build Resilience by Facing Fears",
    "Focus on Solutions, Not Problems",
    "Normalize the Presence of Anxiety",
    "Clarify and Restate Customer Needs",
    "Encourage Open Communication",
    "Balance Empathy with Action",
    "Accept Mistakes as Learning Moments",
    "Break Big Challenges into Smaller Steps",
    "Take Ownership of the Interaction",
    "Cultivate Curiosity About Customers",
    "Practice Non-Reactivity to Criticism",
    "Maintain Consistency Across Interactions",
    "Recognize and Overcome the Upper Limit Problem",
    "Focus on Your Zone of Genius",
    "Reframe Fear as Opportunity",
    "Commit Fully to the Interaction",
    "Develop Awareness of Self-Sabotage",
    "Use Positive Reinforcement",
    "Stay Present in the Moment",
    "Focus on Solutions, Not Problems",
    "Take Ownership of Results",
    "Balance Empathy with Action",
    "Adapt to the Customer’s Emotional State",
    "Normalize Handling Criticism",
    "Prioritize Clarity Over Speed",
    "Develop Resilience Through Reflection",
    "Frame Challenges as Growth Opportunities",
    "Practice Active Listening",
    "Set Intentions for Each Interaction",
    "Use Storytelling to Enhance Engagement",
    "Eliminate Unnecessary Complexity",
    "Acknowledge the Customer’s Effort",
    "Align Suggestions with Customer Goals",
    "Manage Time and Energy Effectively",
    "Stay Calm Under Pressure",
    "Reassure Customers with Confidence",
    "Cultivate Curiosity About the Customer",
    "Celebrate Small Wins",
    "Maintain Emotional Balance",
    "Understand Your Inner Motivations",
    "Develop Your Inner BATNA",
    "Reframe Your Perspective",
    "Stay Present",
    "Respect the Customer, Even If They Are Difficult",
    "Approach Situations with a Win-Win Mindset",
    "Use Empathy to Build Connections",
    "Address the Root Cause, Not Just the Surface Issue",
    "Balance Listening and Speaking",
    "Build Trust Through Consistency",
    "Manage Emotional Reactions",
    "Avoid the Blame Game",
    "Clarify Before Responding",
    "Recognize When to Pause",
    "Use Open-Ended Questions",
    "Value Every Customer Interaction",
    "Lead with Curiosity",
    "Offer Respectful Disagreement",
    "Focus on Long-Term Relationships",
    "Adapt Your Style to the Customer",
    "Show Gratitude",
    "Encourage Feedback",
    "Turn Criticism into Opportunity",
    "Focus on What You Can Control",
    "Use Positive Language",
    "Offer Clear, Concise Solutions",
    "Maintain a Collaborative Mindset",
    "Recognize the Customer’s Efforts",
    "Celebrate Progress",
    "Use Tactical Empathy",
    "Mirror the Customer",
    "Label Emotions",
    "Master the Late-Night FM DJ Voice",
    "Aim for 'That's Right,' Not Just 'Yes'",
    "Avoid Direct 'Yes' or 'No' Questions",
    "Create the Illusion of Control",
    "Be Comfortable with Silence",
    "Use 'No' Strategically",
    "Focus on Interests, Not Positions",
    "Utilize Anchoring",
    "Trigger Reciprocity",
    "Identify Black Swans",
    "Use the Rule of Three",
    "Beware of Splitting the Difference",
    "Focus on Collaboration, Not Confrontation",
    "Use Accusation Audits",
    "Avoid Making Assumptions",
    "Be Proactive in Managing Deadlines",
    "Calibrate Your Questions",
    "Build Psychological Safety",
    "Neutralize Negative Dynamics",
    "Simplify Complex Problems",
    "Make the First Offer When Possible",
    "Demonstrate Patience",
    "Manage Emotional Triggers",
    "Be Specific in Agreements",
    "Maintain Professional Curiosity",
    "Show Appreciation",
    "Use Silence Strategically"
]


@app.get("/tip_of_day")
def get_random_value():
    return {"tip": random.choice(my_list)}


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
